---
- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed | Ubuntu 16.04+"
  apt:
      name: "{{ tcp_wrapper_package[ansible_os_family] }}"
      state: present
      install_recommends: false
  when:
      - ansible_os_family == "Debian"
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.1

- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed | RHEL/CentOS 7+"
  yum:
      name: "{{ tcp_wrapper_package[ansible_os_family] }}"
      state: present
  when:
      - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.1


- name: "SCORED | 3.4.2 | PATCH | Ensure /etc/hosts.allow is configured"
  template:
      src: hosts.allow.j2
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.2

- name: "SCORED | 3.4.3 | PATCH | Ensure /etc/hosts.deny is configured"
  lineinfile:
      dest: /etc/hosts.deny
      regexp: "^(#)?ALL"
      line: "ALL: ALL"
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.3

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.4

- name: "SCORED | 3.4.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  file:
      dest: /etc/hosts.deny
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - scored
      - patch
      - rule_3.4.5
