---
- name: "SCORED | 1.6.1.1 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      follow: true
  register: selinux_grub_patch
  ignore_errors: true
  notify: generate new grub config
  when:
      - cis_dil_rule_1_6_1_1
  tags:
      - level2
      - scored
      - patch
      - rule_1.6.1.1

- name: "SCORED | 1.6.1.2 | PATCH | Ensure the SELinux state is enforcing"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_2
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.1.2
      - notimplemented

- name: "SCORED | 1.6.1.3 | PATCH | Ensure SELinux policy is configured"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_3
  tags:
      - level1
      - scored
      - patc3
      - rule_1.6.1.3
      - notimplemented

- name: "SCORED | 1.6.1.4 | PATCH | Ensure SETroubleshoot is not installed"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_4
  tags:
      - level1
      - scored
      - patc3
      - rule_1.6.1.4
      - notimplemented

- name: "SCORED | 1.6.1.5 | PATCH | Ensure the MCS Translation Service (mcstrans) is nost installed"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_5
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.1.5
      - notimplemented

- name: "SCORED | 1.6.1.6 | PATCH | Ensure no unconfined daemons exist"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_6
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.1.6
      - notimplemented

- name: "SCORED | 1.6.2.1 | PATCH | Ensure AppArmor is not disabled in bootloader configuration"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_2_1
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.2.1
      - notimplemented

- name: "SCORED | 1.6.2.2 | PATCH | Ensure all AppArmor Profiles are enforcing"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_2_2
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.2.2
      - notimplemented

- name: "SCORED | 1.6.3 | PATCH | Ensure SELinux or AppArmor are installed"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_3
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.3
      - notimplemented
