---
- name: "SCORED | 1.3.1 | PATCH | Ensure AIDE is installed"
  apt:
      name: aide
      state: present
      install_recommends: false
  when:
      - cis_dil_rule_1_3_1
  tags:
      - level1
      - scored
      - aide
      - patch
      - rule_1.3.1

- name: "SCORED | 1.3.1 | PATCH | Ensure AIDE is installed"
  command: /usr/bin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
      creates: /var/lib/aide/aide.db.gz
  changed_when: false
  failed_when: false
  async: 45
  poll: 0
  when:
      - cis_dil_config_aide
      - cis_dil_rule_1_3_1
  tags:
      - level1
      - scored
      - aide
      - patch
      - rule_1.3.1

- name: "SCORED | 1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check weekly
      cron_file: "{{ cis_dil_aide_cron['cron_file'] }}"
      user: "{{ cis_dil_aide_cron['cron_user'] }}"
      minute: "{{ cis_dil_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ cis_dil_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ cis_dil_aide_cron['aide_day'] | default('*') }}"
      month: "{{ cis_dil_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ cis_dil_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ cis_dil_aide_cron['aide_job'] }}"
  when:
      - cis_dil_rule_1_3_2
  tags:
      - level1
      - scored
      - aide
      - file_integrity
      - patch
      - rule_1.3.2
