---
# tasks file for Ubuntu1604-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Ubuntu 16.04+ or RHEL/CentOS 7+ {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: ( (ansible_distribution == "Ubuntu") and (ansible_distribution_major_version | int < 16) ) or
        ( ( (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat") ) and (ansible_distribution_major_version | int < 7) )
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include: prelim.yml
  become: true
  tags:
      - prelim_tasks
      - always

- include: section1/section1.1.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_1
  tags:
   - section1
   - section1.1

- include: section1/section1.2.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_2
  tags:
   - section1
   - section1.2

- include: section1/section1.3.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_3
  tags:
   - section1
   - section1.3

- include: section1/section1.4.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_4
  tags:
   - section1
   - section1.4

- include: section1/section1.5.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_5
  tags:
   - section1
   - section1.5

- include: section1/section1.6.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_6
  tags:
   - section1
   - section1.6

- include: section1/section1.7.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_7
  tags:
   - section1
   - section1.7

- include: section1/section1.8.yml
  become: true
  when:
    - cis_dil_section1
    - cis_dil_section1_8
  tags:
   - section1
   - section1.8

- include: section2/section2.1.yml
  become: true
  when:
    - cis_dil_section2
    - cis_dil_section2_1
  tags:
    - section2
    - section2.1

- include: section2/section2.2.yml
  become: true
  when:
    - cis_dil_section2
    - cis_dil_section2_2
  tags:
    - section2
    - section2.2

- include: section2/section2.3.yml
  become: true
  when:
    - cis_dil_section2
    - cis_dil_section2_3
  tags:
    - section2
    - section2.3

- include: section3/section3.1.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_1
  tags:
    - section3
    - section3.1

- include: section3/section3.2.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_2
  tags:
    - section3
    - section3.2

- include: section3/section3.3.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_3
  tags:
    - section3
    - section3.3

- include: section3/section3.4.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_4
  tags:
    - section3
    - section3.4

- include: section3/section3.5.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_5
  tags:
    - section3
    - section3.5

- include: section3/section3.6.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_6
  tags:
    - section3
    - section3.6

- include: section3/section3.7.yml
  become: true
  when:
    - cis_dil_section3
    - cis_dil_section3_7
  tags:
    - section3
    - section3.7

- include: section4/section4.1.yml
  become: true
  when:
    - cis_dil_section4
    - cis_dil_section4_1
  tags:
    - section4
    - section4.1

- include: section4/section4.2.yml
  become: true
  when:
    - cis_dil_section4
    - cis_dil_section4_2
  tags:
    - section4
    - section4.2

- include: section4/section4.3.yml
  become: true
  when:
    - cis_dil_section4
    - cis_dil_section4_3
  tags:
    - section4
    - section4.3

- include: section5/section5.1.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_1
  tags:
    - section5
    - section5.1

- include: section5/section5.2.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_2
  tags:
    - section5
    - section5.2

- include: section5/section5.3.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_3
  tags:
    - section5
    - section5.3

- include: section5/section5.4.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_4
  tags:
    - section5
    - section5.4

- include: section5/section5.5.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_5
  tags:
    - section5
    - section5.5

- include: section5/section5.6.yml
  become: true
  when:
    - cis_dil_section5
    - cis_dil_section5_6
  tags:
    - section5
    - section5.6

- include: section6.yml
  become: true
  when: cis_dil_section6
  tags: section6

- include: post.yml
  become: true
  tags:
      - post_tasks
      - always
