---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: false
  check_mode: false

- name: "PRELIM | Gather accounts with empty password fields"
  shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  register: empty_password_accounts
  changed_when: false
  check_mode: false

- name: "PRELIM | Gather UID 0 accounts other than root"
  shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  register: uid_zero_accounts_except_root
  changed_when: false
  check_mode: false

- name: "PRELIM | Run apt cache update | Ubuntu 16.04+"
  apt:
    update_cache: true
  when:
    - ansible_os_family == "Debian"
  changed_when: false

- name: "PRELIM | Refresh yum repo cache | RHEL/CentOS 7+"
  yum:
    name: "*"
    update_cache: yes
    state: present
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
  changed_when: false


- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd) | Ubuntu 16.04+"
  apt:
    name: "{{ auditd_package[ansible_os_family] }}"
    state: present
    install_recommends: false
  when:
    - ansible_os_family == "Debian"

- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd) | RHEL/CentOS 7+"
  yum:
    name: "{{ auditd_package[ansible_os_family] }}"
    state: present
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: "PRELIM | Section 5.1 | Configure cron | Ubuntu 16.04+"
  apt:
    name: "{{ cron_package[ansible_os_family] }}"
    state: present
    install_recommends: false
  when:
    - ansible_os_family == "Debian"


- name: "PRELIM | Section 5.1 | Configure cron | RHEL/CentOS 7+"
  yum:
    name: "{{ cron_package[ansible_os_family] }}"
    state: present
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")


- name: "PRELIM | Check if prelink package is installed"
  command: "{{ prelim_check_package_command[ansible_os_family] }} prelink"
  register: prelink_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

- name: "PRELIM | Check if postfix package is installed"
  command: "{{ prelim_check_package_command[ansible_os_family] }} postfix"
  register: postfix_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - skip_ansible_lint

# Individual service checks
- name: "PRELIM | Check for xinetd service"
  shell: "systemctl show xinetd | grep LoadState | cut -d = -f 2"
  register: xinetd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check if we are using chrony | Ubuntu 16.04+"
  shell: dpkg --get-selections | grep -o chrony
  register: using_chrony
  changed_when: false
  failed_when: false
  check_mode: false
  when:
    - ansible_os_family == "Debian"

- name: "PRELIM | Check if we are using chrony | RHEL/CentOS 7+"
  shell: rpm -aq | grep -o chrony
  register: using_chrony
  changed_when: false
  failed_when: false
  check_mode: false
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: "PRELIM | Check if we are using ntp | Ubuntu 16.04+"
  shell: dpkg --get-selections | grep -o ntp
  register: using_ntp
  changed_when: false
  failed_when: false
  check_mode: false
  when:
    - ansible_os_family == "Debian"

- name: "PRELIM | Check if we are using ntp | RHEL/CentOS 7+"
  shell: rpm -aq | grep -o ntp
  register: using_ntp
  changed_when: false
  failed_when: false
  check_mode: false
  when:
    - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")

- name: "PRELIM | Check for ntpd service"
  shell: "systemctl show {{ ntp_service[ansible_os_family] }} | grep LoadState | cut -d = -f 2"
  register: ntpd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for chronyd service"
  shell: "systemctl show {{ chrony_service[ansible_os_family] }} | grep LoadState | cut -d = -f 2"
  register: chronyd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | If no time service installed or configured then lets use chrony"
  set_fact:
    cis_dil_time_synchronization_service: "chrony"
  failed_when: false
  when:
    - using_chrony is skipped
    - using_ntp is skipped
    - (cis_dil_time_synchronization_service != "ntp") or (cis_dil_time_synchronization_service != "chrony")

- name: "PRELIM | set ntp as time service if it is installed"
  set_fact:
    cis_dil_time_synchronization_service: "ntp"
  failed_when: false
  when:
    - using_ntp is not skipped
    - using_ntp.rc == "0"

- name: "PRELIM | Check for avahi-daemon service"
  shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for cups service"
  shell: "systemctl show cups | grep LoadState | cut -d = -f 2"
  register: cups_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for dhcpd service"
  shell: "systemctl show dhcpd | grep LoadState | cut -d = -f 2"
  register: dhcpd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for slapd service"
  shell: "systemctl show slapd | grep LoadState | cut -d = -f 2"
  register: slapd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for nfs service"
  shell: "systemctl show nfs | grep LoadState | cut -d = -f 2"
  register: nfs_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rpcbind service"
  shell: "systemctl show rpcbind | grep LoadState | cut -d = -f 2"
  register: rpcbind_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for named service"
  shell: "systemctl show named | grep LoadState | cut -d = -f 2"
  register: named_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for vsftpd service"
  shell: "systemctl show vsftpd | grep LoadState | cut -d = -f 2"
  register: vsftpd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for httpd service"
  shell: "systemctl show httpd | grep LoadState | cut -d = -f 2"
  register: httpd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for dovecot service"
  shell: "systemctl show dovecot | grep LoadState | cut -d = -f 2"
  register: dovecot_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for smb service"
  shell: "systemctl show smb | grep LoadState | cut -d = -f 2"
  register: smb_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for squid service"
  shell: "systemctl show squid | grep LoadState | cut -d = -f 2"
  register: squid_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for snmpd service"
  shell: "systemctl show snmpd | grep LoadState | cut -d = -f 2"
  register: snmpd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for ypserv service"
  shell: "systemctl show ypserv | grep LoadState | cut -d = -f 2"
  register: ypserv_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rsh.socket service"
  shell: "systemctl show rsh.socket | grep LoadState | cut -d = -f 2"
  register: rsh_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rlogin.socket service"
  shell: "systemctl show rlogin.socket | grep LoadState | cut -d = -f 2"
  register: rlogin_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rexec.socket service"
  shell: "systemctl show rexec.socket | grep LoadState | cut -d = -f 2"
  register: rexec_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for telnet service"
  shell: "systemctl show telnet | grep LoadState | cut -d = -f 2"
  register: telnet_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for tftp service"
  shell: "systemctl show tftp | grep LoadState | cut -d = -f 2"
  register: tftp_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rsyncd service"
  shell: "systemctl show rsyncd | grep LoadState | cut -d = -f 2"
  register: rsyncd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for ntalk service"
  shell: "systemctl show ntalk | grep LoadState | cut -d = -f 2"
  register: ntalk_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for autofs service"
  shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: autofs_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check for rhnsd service"
  shell: "systemctl show rhnsd | grep LoadState | cut -d = -f 2"
  register: rhnsd_service_status
  changed_when: false
  check_mode: false

- name: "PRELIM | Check the grub configuration"
  stat:
    path: /boot/grub/grub.cfg
  register: grub_cfg
