---
- name: "SCORED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      state: present
      owner: root
      group: root
      mode: 0644
      create: true
  when:
      - cis_dil_rule_1_1_1_1
  tags:
      - level1
      - scored
      - patch
      - cramfs
      - filesystems
      - rule_1.1.1.1

- name: "SCORED | 1.1.1.1 | PATCH | Remove cramfs module"
  modprobe:
      name: cramfs
      state: absent
  when:
      - cis_dil_rule_1_1_1_1
  tags:
      - level1
      - scored
      - patch
      - cramfs
      - filesystems
      - rule_1.1.1.1

- name: "SCORED | 1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install freevxfs"
      line: "install freevxfs /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_2
  tags:
      - level1
      - scored
      - patch
      - freevxfs
      - filesystems
      - rule_1.1.1.2

- name: "SCORED | 1.1.1.2 | PATCH | Remove freevxfs module"
  modprobe:
      name: freevxfs
      state: absent
  when:
      - cis_dil_rule_1_1_1_2
  tags:
      - level1
      - scored
      - patch
      - freevxfs
      - filesystems
      - rule_1.1.1.2

- name: "SCORED | 1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install jffs2(\\s|$)"
      line: "install jffs2 /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_3
  tags:
      - level1
      - scored
      - patch
      - jffs2
      - filesystems
      - rule_1.1.1.3

- name: "SCORED | 1.1.1.3 | PATCH | Remove jffs2 module"
  modprobe:
      name: jffs2
      state: absent
  when:
      - cis_dil_rule_1_1_1_3
  tags:
      - level1
      - scored
      - patch
      - jffs2
      - filesystems
      - rule_1.1.1.3

- name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfs(\\s|$)"
      line: "install hfs /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_4
  tags:
      - level1
      - scored
      - patch
      - hfs
      - filesystems
      - rule_1.1.1.4

- name: "SCORED | 1.1.1.4 | PATCH | Remove hfs module"
  modprobe:
      name: hfs
      state: absent
  when:
      - cis_dil_rule_1_1_1_4
  tags:
      - level1
      - scored
      - patch
      - hfs
      - filesystems
      - rule_1.1.1.4

- name: "SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfsplus(\\s|$)"
      line: "install hfsplus /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_5
  tags:
      - level1
      - scored
      - patch
      - hfsplus
      - filesystems
      - rule_1.1.1.5

- name: "SCORED | 1.1.1.5 | PATCH | Remove hfsplus module"
  modprobe:
      name: hfsplus
      state: absent
  when:
      - cis_dil_rule_1_1_1_5
  tags:
      - level1
      - scored
      - patch
      - hfsplus
      - filesystems
      - rule_1.1.1.5

- name: "SCORED | 1.1.1.6 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_6
  tags:
      - level1
      - scored
      - patch
      - squashfs
      - filesystems
      - rule_1.1.1.6

- name: "SCORED | 1.1.1.6 | PATCH | Remove squashfs module"
  modprobe:
      name: squashfs
      state: absent
  when:
      - cis_dil_rule_1_1_1_6
  tags:
      - level1
      - scored
      - patch
      - squashfs
      - filesystems
      - rule_1.1.1.6

- name: "SCORED | 1.1.1.7 | PATCH | Ensure mounting of udf filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_7
  tags:
      - level1
      - scored
      - patch
      - udf
      - filesystems
      - rule_1.1.1.7

- name: "SCORED | 1.1.1.7 | PATCH | Remove udf module"
  modprobe:
      name: udf
      state: absent
  when:
      - cis_dil_rule_1_1_1_7
  tags:
      - level1
      - scored
      - patch
      - udf
      - filesystems
      - rule_1.1.1.7

- name: "SCORED | 1.1.1.8 | PATCH | Ensure mounting of FAT filesystems is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install vfat(\\s|$)"
      line: "install vfat /bin/true"
      state: present
      create: true
  when:
      - cis_dil_rule_1_1_1_8
  tags:
      - level1
      - scored
      - patch
      - vfat
      - filesystems
      - rule_1.1.1.8

- name: "SCORED | 1.1.1.8 | PATCH | Remove FAT module"
  modprobe:
      name: vfat
      state: absent
  when:
      - cis_dil_rule_1_1_1_8
  tags:
      - level2
      - scored
      - patch
      - vfat
      - filesystems
      - rule_1.1.1.8

- name: "SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | enable and start/restart tmp.mount"
  copy:
      src: "{{ tmp_mount_file[ansible_os_family] }}"
      dest: /etc/systemd/system/tmp.mount
      owner: root
      group: root
      mode: 0644
      force: true
      remote_src: true
  notify:
      - systemd restart tmp.mount
  when:
      - cis_dil_rule_1_1_2
      - cis_dil_skip_for_travis == false
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.2

- name: "SCORED | 1.1.2 | PATCH | Ensure separate partition exists for /tmp | enable and start/restart tmp.mount"
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: started
  when:
      - cis_dil_rule_1_1_2
      - cis_dil_skip_for_travis == false
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.2

- name: "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition\n
         SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition\n
         SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition\n
         | drop custom tmp.mount"
  ini_file:
      path: "{{ item }}"
      section: Mount
      option: Options
      value: "{{ tmp_mount_options[ansible_os_family] }}"
      no_extra_spaces: true
  with_items:
      - "{{ tmp_mount_file[ansible_os_family] }}"
      - /etc/systemd/system/tmp.mount
  notify:
      - systemd restart tmp.mount
  when:
      - cis_dil_rule_1_1_3
      - cis_dil_rule_1_1_4
      - cis_dil_rule_1_1_5
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5

- name: "SCORED | 1.1.6 | PATCH | Ensure separate partition exists for /var"
  shell: mount | grep "on /var "
  register: var_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_6
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.6
      - skip_ansible_lint

- name: "SCORED | 1.1.7 | PATCH | Ensure separate partition exists for /var/tmp"
  shell: mount | grep "on /var/tmp "
  register: var_tmp_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_7
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.7
      - skip_ansible_lint

# There is an error in tge v1.1.0 Benchmark mentioning the noexec settings too many times
- name: "SCORED | 1.1.8  | PATCH | Ensure nodev option set on /var/tmp partition\n
         SCORED | 1.1.9  | PATCH | Ensure nosuid option set on /var/tmp partition\n
         SCORED | 1.1.10 | PATCH | Ensure noexec option set on /var/tmp partition\n
         SCORED | 1.1.11 | PATCH | Ensure noexec option set on /var/tmp partition\n
         SCORED | 1.1.12 | PATCH | Ensure noexec option set on /var/tmp partition\n
         SCORED | 1.1.13 | PATCH | Ensure noexec option set on /var/tmp partition\n
         SCORED | 1.1.14 | PATCH | Ensure noexec option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ cis_dil_vartmp['source'] }}"
      state: mounted
      fstype: "{{ cis_dil_vartmp['fstype'] }}"
      opts: "{{ cis_dil_vartmp['opts'] }}"
  when:
      - cis_dil_vartmp['enabled'] == 'yes'
      - cis_dil_rule_1_1_7
      - cis_dil_rule_1_1_8
      - cis_dil_rule_1_1_9
      - cis_dil_rule_1_1_10
      - cis_dil_rule_1_1_11
      - cis_dil_rule_1_1_12
      - cis_dil_rule_1_1_13
      - cis_dil_rule_1_1_14
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.7
      - rule_1.1.8
      - rule_1.1.9
      - rule_1.1.10
      - rule_1.1.11
      - rule_1.1.12
      - rule_1.1.13
      - rule_1.1.14

- name: "SCORED | 1.1.15 | PATCH | Ensure separate partition exists for /var/log"
  shell: mount | grep "on /var/log "
  register: var_log_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_15
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.15
      - skip_ansible_lint

- name: "SCORED | 1.1.16 | PATCH | Ensure separate partition exists for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: var_log_audit_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_16
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.16
      - skip_ansible_lint

- name: "SCORED | 1.1.17 | PATCH | Ensure separate partition exists for /home"
  shell: mount | grep "on /home "
  register: home_mounted
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_17
  tags:
      - level2
      - scored
      - patch
      - rule_1.1.17
      - skip_ansible_lint

- name: "SCORED | 1.1.18 | PATCH | Ensure nodev option set on /home partition"
  mount:
      name: "/home"
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "nodev"
  when:
      - cis_dil_rule_1_1_18
      - item.mount == "/home"
  with_items:
      - "{{ ansible_mounts }}"
  tags:
      - scored
      - level1
      - patch
      - rule_1.1.18

- name: "SCORED | 1.1.19 | PATCH | Ensure nodev option set on /dev/shm partition\n
         SCORED | 1.1.20 | PATCH | Ensure nosuid option set on /dev/shm partition\n
         SCORED | 1.1.21 | PATCH | Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "defaults,nodev,nosuid,noexec"
  when:
      - cis_dil_rule_1_1_19
      - cis_dil_rule_1_1_20
      - cis_dil_rule_1_1_21
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.19
      - rule_1.1.20
      - rule_1.1.21

- name: "NOTSCORED | 1.1.22 | PATCH | Ensure nodev option set on removable media partitions"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_1_22
  tags:
      - level1
      - notscored
      - patch
      - rule_1.1.22
      - notimplemented

- name: "NOTSCORED | 1.1.23 | PATCH | Ensure nosuid option set on removable media partitions"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_1_23
  tags:
      - level1
      - notscored
      - patch
      - rule_1.1.23
      - notimplemented

- name: "NOTSCORED | 1.1.24 | PATCH | Ensure noexec option set on removable media partitions"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_1_24
  tags:
      - level1
      - notscored
      - patch
      - rule_1.1.24
      - notimplemented

- name: "SCORED | 1.1.25 | PATCH | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_1_1_25
      # - sticky_bit_on_worldwritable_dirs_audit.rc == '0'
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.25

- name: "SCORED | 1.1.26 | PATCH | Disable Automounting"
  service:
      name: autofs
      enabled: false
  when:
      - cis_dil_allow_autofs == false and autofs_service_status.stdout == "loaded"
      - cis_dil_rule_1_1_26
  tags:
      - level1
      - scored
      - patch
      - rule_1.1.26
