---
- name: "NOTSCORED | 1.2.1 | PATCH | Ensure package manager repositories are configured"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_2_1
  tags:
      - level1
      - notscored
      - patch
      - rule_1.2.1


- name: "NOTSCORED | 1.2.3 | PATCH | Ensure GPG keys are configured"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_2_3
  tags:
      - level1
      - notscored
      - patch
      - rule_1.2.3
      - notimplemented

- name: "SCORED | 1.3.1 | PATCH | Ensure AIDE is installed"
  apt:
      name: aide
      state: present
      install_recommends: false
  when:
      - cis_dil_rule_1_3_1
  tags:
      - level1
      - scored
      - aide
      - patch
      - rule_1.3.1

- name: "SCORED | 1.3.1 | PATCH | Ensure AIDE is installed"
  command: /usr/bin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
      creates: /var/lib/aide/aide.db.gz
  changed_when: false
  failed_when: false
  async: 45
  poll: 0
  when:
      - cis_dil_config_aide
      - cis_dil_rule_1_3_1
  tags:
      - level1
      - scored
      - aide
      - patch
      - rule_1.3.1

- name: "SCORED | 1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check weekly
      cron_file: "{{ cis_dil_aide_cron['cron_file'] }}"
      user: "{{ cis_dil_aide_cron['cron_user'] }}"
      minute: "{{ cis_dil_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ cis_dil_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ cis_dil_aide_cron['aide_day'] | default('*') }}"
      month: "{{ cis_dil_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ cis_dil_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ cis_dil_aide_cron['aide_job'] }}"
  when:
      - cis_dil_rule_1_3_2
  tags:
      - level1
      - scored
      - aide
      - file_integrity
      - patch
      - rule_1.3.2

- name: "SCORED | 1.4.1 | PATCH | Ensure permissions on bootloader config are configured"
  file:
      path: "/boot/grub/grub.cfg"
      owner: root
      group: root
      mode: 0600
  when: 
      - ansible_os_family == "Debian"
      - cis_dil_rule_1_4_1
  tags:
      - level1
      - scored
      - grub
      - patch
      - rule_1.4.1

- name: "SCORED | 1.4.2 | PATCH | Ensure bootloader password is set"
  grub_crypt:
      password: "{{ cis_dil_bootloader_password }}"
  register: grub_pass
  when:
      - cis_dil_set_boot_pass
      - cis_dil_rule_1_4_2
  tags:
      - level1
      - scored
      - grub
      - patch
      - rule_1.4.2
      - notimplemented

- name: "NOTSCORED | 1.4.3 | PATCH | Ensure authentication required for single user mode"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_4_3
  tags:
      - level1
      - notscored
      - patch
      - rule_1.4.3
      - notimplemented

- name: "SCORED | 1.5.1 | PATCH | Ensure core dumps are restricted"
  lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'
  when:
      - cis_dil_rule_1_5_1
  tags:
      - level1
      - scored
      - limits
      - patch
      - rule_1.5.1

- name: "SCORED | 1.5.1 | PATCH | Ensure core dumps are restricted"
  sysctl:
      name: fs.suid_dumpable
      value: 0
      state: present
      reload: true
      sysctl_set: true
      ignoreerrors: true
  when:
      - cis_dil_rule_1_5_1
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_1.5.1

- name: "NOTSCORED | 1.5.2 | PATCH | Ensure XD/NX support is enabled"
  shell: dmesg | grep -E "NX|XD" | grep " active"
  changed_when: false
  when:
      - cis_dil_rule_1_5_2
  tags:
      - level1
      - notscored
      - patch
      - rule_1.5.2
      - notimplemented

- name: "SCORED | 1.5.3 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: 2
      state: present
      reload: true
      sysctl_set: true
      ignoreerrors: true
  when:
      - cis_dil_rule_1_5_3
  tags:
      - level1
      - scored
      - patch
      - sysctl
      - rule_1.5.3

- name: "SCORED | 1.5.4 | PATCH | Ensure prelink is disabled"
  command: prelink -ua
  when:
      - prelink_installed.rc == 0
      - cis_dil_rule_1_5_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.5.4

- name: "SCORED | 1.5.4 | PATCH | Ensure prelink is disabled"
  apt:
      name: prelink
      state: absent
  when:
      - cis_dil_rule_1_5_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.5.4

- name: "SCORED | 1.6.1.1 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
      follow: true
  register: selinux_grub_patch
  ignore_errors: true
  notify: generate new grub config
  when:
      - cis_dil_rule_1_6_1_1
  tags:
      - level2
      - scored
      - patch
      - rule_1.6.1.1

- name: "SCORED | 1.6.1.2 | PATCH | Ensure the SELinux state is enforcing"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_2
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.1.2
      - notimplemented

- name: "SCORED | 1.6.1.3 | PATCH | Ensure SELinux policy is configured"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_3
  tags:
      - level1
      - scored
      - patc3
      - rule_1.6.1.2
      - notimplemented

- name: "SCORED | 1.6.1.4 | PATCH | Ensure no unconfined daemons exist"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.1.4
      - notimplemented

- name: "SCORED | 1.6.2.1 | PATCH | Ensure AppArmor is not disabled in bootloader configuration"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_2_1
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.2.1
      - notimplemented

- name: "SCORED | 1.6.2.2 | PATCH | Ensure all AppArmor Profiles are enforcing"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_2_2
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.2.2
      - notimplemented

- name: "SCORED | 1.6.3 | PATCH | Ensure SELinux or AppArmor are installed"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_1_6_3
  tags:
      - level1
      - scored
      - patch
      - rule_1.6.3
      - notimplemented


- name: "SCORED | 1.7.1.1 | PATCH | Ensure message of the day is configured properly"
  template:
      src: etc/motd.j2
      dest: /etc/motd
  when:
      - cis_dil_rule_1_7_1_1
  tags:
      - level1
      - scored
      - patch
      - banner
      - rule_1.7.1.1

- name: "NOTSCORED | 1.7.1.2 | PATCH | Ensure local login warning banner is configured properly"
  template:
      src: etc/issue.j2
      dest: /etc/issue
  when:
      - cis_dil_rule_1_7_1_2
  tags:
      - level1
      - notscored
      - patch
      - banner
      - rule_1.7.1.2

- name: "NOTSCORED | 1.7.1.3 | PATCH | Ensure remote login warning banner is configured properly"
  template:
      src: etc/issue.net.j2
      dest: /etc/issue.net
  when:
      - cis_dil_rule_1_7_1_3
  tags:
      - level1
      - notscored
      - patch
      - banner
      - rule_1.7.1.3

- name: "NOTSCORED | 1.7.1.4 | PATCH | Ensure permissions on /etc/motd are configured"
  file:
      dest: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - cis_dil_rule_1_7_1_4
  tags:
      - level1
      - notscored
      - patch
      - perms
      - rule_1.7.1.4

- name: "SCORED | 1.7.1.5 | PATCH | Ensure permissions on /etc/issue are configured"
  file:
      dest: /etc/issue
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - cis_dil_rule_1_7_1_5
  tags:
      - level1
      - scored
      - patch
      - perms
      - rule_1.7.1.5

- name: "NOTSCORED | 1.7.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  file:
      dest: /etc/issue.net
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - cis_dil_rule_1_7_1_6
  tags:
      - level1
      - notscored
      - patch
      - perms
      - rule_1.7.1.6

- name: "SCORED | 1.7.2 | PATCH | Ensure GDM login banner is configured"
  lineinfile:
      dest: "{{ item.file }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: true
      owner: root
      group: root
      mode: 0644
  with_items:
      - { file: '/etc/dconf/profile/gdm', regexp: 'user-db', line: 'user-db:user' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'system-db', line: 'system-db:gdm' }
      - { file: '/etc/dconf/profile/gdm', regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
      - { file: '/etc/dconf/db/gdm.d/01-banner-message', regexp: 'banner-message-text', line: "banner-message-text='{{ cis_dil_warning_banner }}' " }
  when:
      - cis_dil_gui
      - cis_dil_rule_1_7_2
  tags:
      - level1
      - scored
      - patch
      - banner
      - rule_1.7.2

- name: "NOTSCORED | 1.8 | PATCH | Ensure updates, patches, and additional security software are installed"
  apt:
      upgrade: dist
  tags:
      - level1
      - notscored
      - patch
      - rule_1.8
      - skip_ansible_lint
