---
- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
      dest: /etc/ssh/sshd_config
      state: file
      owner: root
      group: root
      mode: 0600
  when:
      - cis_dil_rule_5_2_1
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure SSH Protocol is set to 2"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Protocol'
      line: 'Protocol 2'
  when:
      - cis_dil_rule_5_2_2
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure SSH LogLevel is set to INFO"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LogLevel'
      line: 'LogLevel INFO'
  when:
      - cis_dil_rule_5_2_3
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.3

- name: "SCORED | 5.2.4 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'
  when:
      - cis_dil_rule_5_2_4
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.4

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxAuthTries \d'
      line: 'MaxAuthTries 4'
  when:
      - cis_dil_rule_5_2_5
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  when:
      - cis_dil_rule_5_2_6
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  when:
      - cis_dil_rule_5_2_7
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
  when:
      - cis_dil_rule_5_2_8
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  when:
      - cis_dil_rule_5_2_9
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  when:
      - cis_dil_rule_5_2_10
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.10

- name: "SCORED | 5.2.11 | PATCH | Ensure only approved MAC algorithms are used"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^MACs'
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  when:
      - cis_dil_rule_5_2_11
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
      - name: "SCORED | 5.2.12 | PATCH | Ensure SSH Idle Timeout Interval is configured"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveInterval'
            line: "ClientAliveInterval {{ cis_dil_sshd['clientaliveinterval'] }}"

      - name: "SCORED | 5.2.12 | PATCH | Ensure SSH ClientAliveCountMax set to <= 3"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^ClientAliveCountMax'
            line: "ClientAliveCountMax {{ cis_dil_sshd['clientalivecountmax'] }}"
  when:
      - cis_dil_rule_5_2_12
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.12

- name: "SCORED | 5.2.13 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime'
      line: "LoginGraceTime 60"
  when:
      - cis_dil_rule_5_2_13
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.13

- name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited"
  block:
      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - allowusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowUsers'
            line: "AllowUsers {{ cis_dil_sshd['allowusers'] }}"
        notify:
            - restart sshd
        when:
            - "cis_dil_sshd['allowusers']|default('') != ''"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - allowgroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^AllowGroups'
            line: "AllowGroups {{ cis_dil_sshd['allowgroups'] }}"
        notify:
            - restart sshd
        when:
            - "cis_dil_sshd['allowgroups']|default('') != ''"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - denyusers"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyUsers'
            line: "DenyUsers {{ cis_dil_sshd['denyusers'] }}"
        notify:
            - restart sshd
        when:
            - "cis_dil_sshd['denyusers']|default('') != ''"

      - name: "SCORED | 5.2.14 | PATCH | Ensure SSH access is limited - denygroups"
        lineinfile:
            state: present
            dest: /etc/ssh/sshd_config
            regexp: '^DenyGroups'
            line: "DenyGroups {{ cis_dil_sshd['denygroups'] }}"
        notify:
            - restart sshd
        when:
            - "cis_dil_sshd['denygroups']|default('') != ''"
  when:
      - cis_dil_rule_5_2_14
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^Banner'
      line: 'Banner /etc/issue.net'
  when:
      - cis_dil_rule_5_2_15
  tags:
      - level1
      - scored
      - patch
      - sshd
      - rule_5.2.15
