---
- name: "SCORED | 5.4.1.1 | PATCH | Ensure password expiration is 365 days or less"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MAX_DAYS'
      line: "PASS_MAX_DAYS {{ cis_dil_pass['max_days'] }}"
  when:
      - cis_dil_rule_5_4_1_1
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.1

- name: "SCORED | 5.4.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_MIN_DAYS'
      line: "PASS_MIN_DAYS {{ cis_dil_pass['min_days'] }}"
  when:
      - cis_dil_rule_5_4_1_2
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.2

- name: "SCORED | 5.4.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  lineinfile:
      state: present
      dest: /etc/login.defs
      regexp: '^PASS_WARN_AGE'
      line: "PASS_WARN_AGE {{ cis_dil_pass['warn_age'] }}"
  when:
      - cis_dil_rule_5_4_1_3
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.3

- name: "SCORED | 5.4.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_4_1_4
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.4
      - notimplemented

- name: "SCORED | 5.4.1.5 | PATCH | Ensure all users last password change date is in the past"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_4_1_5
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.1.5
      - notimplemented

- name: "SCORED | 5.4.2 | PATCH | Ensure system accounts are non-login"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_4_2
  tags:
      - level1
      - patch
      - rule_5.4.2
      - notimplemented
      - scored

- name: "SCORED | 5.4.3 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_5_4_3
  tags:
      - level1
      - patch
      - rule_5.4.3
      - scored

- name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive"
  block:

      - name: "SCORED | 5.4.4 | PATCH | Check if bashrc exists"
        stat:
            path: "/etc/bashrc"
        register: bashrc_present

      - name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/bashrc"
        replace:
            path: /etc/bashrc
            regexp: '(^\s+umask) 002'
            replace: '\1 027'
        when: bashrc_present.stat.exists

      - name: "SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/profile"
        replace:
            path: /etc/profile
            regexp: '(^\s+umask) 002'
            replace: '\1 027'
  when:
      - cis_dil_rule_5_4_4
  tags:
      - level1
      - patch
      - rule_5.4.4
      - scored

- name: "SCORED | 5.4.5 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_4_5
  tags:
      - level1
      - scored
      - patch
      - rule_5.4.5
      - notimplemented
