---
- name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
  block:
      - name: "SCORED | 5.3.1 | PATCH | Ensure lipam-pwquality is installed | Ubuntu 16.04+"
        apt:
            name: libpam-pwquality
            state: present
            install_recommends: false
        when:
            - ansible_os_family == "Debian"

      - name: "SCORED | 5.3.1 | PATCH | Ensure lipam-pwquality is installed | RHEL/CentOS 7+"
        yum:
            name: libpwquality
            state: present
        when:
            - (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")


      - name: "SCORED | 5.3.1 | PATCH | Ensure password creation requirements are configured"
        lineinfile:
            state: present
            dest: /etc/security/pwquality.conf
            regexp: '^{{ item.key }}'
            line: '{{ item.key }} = {{ item.value }}'
        with_items:
            - { key: 'minlen', value: '14' }
            - { key: 'dcredit', value: '-1' }
            - { key: 'ucredit', value: '-1' }
            - { key: 'ocredit', value: '-1' }
            - { key: 'lcredit', value: '-1' }
  when:
      - cis_dil_rule_5_3_1
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.1

- name: "SCORED | 5.3.2 | PATCH | Ensure lockout for failed password attempts is configured"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_3_2
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.2
      - notimplemented

- name: "SCORED | 5.3.3 | PATCH | Ensure password reuse is limited"
  command: /bin/true
  changed_when: false
  when:
      - cis_dil_rule_5_3_3
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.3
      - notimplemented

- name: "SCORED | 5.3.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  command: authconfig --passalgo=sha512 --update
  changed_when: false
  failed_when: false
  when:
      - cis_dil_rule_5_3_4
  tags:
      - level1
      - scored
      - patch
      - rule_5.3.4
