---
- name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
  block:
      - name: "NOTSCORED | 4.3 | PATCH | Register logrotate.d files"
        find:
            paths: /etc/logrotate.d/
        register: log_rotates

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate.conf exists"
        file:
            path: /etc/logrotate.conf
            state: touch
        changed_when: false

      - name: "NOTSCORED | 4.3 | PATCH | Ensure logrotate is configured"
        replace:
            path: "{{ item.path }}"
            regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
            replace: "\\1{{ cis_dil_logrotate }}"
        with_items:
            - "{{ log_rotates.files }}"
            - { path: "/etc/logrotate.conf" }
  when:
      - cis_dil_rule_4_3
  tags:
      - level1
      - notscored
      - patch
      - syslog
      - rule_4.3
